<?php

declare( strict_types = 1 );

namespace oihana\middleware\tracing ;

use oihana\middleware\enums\ParsedTraceparentField ;

/**
 * Parses a raw `traceparent` header value into its W3C Trace Context
 * components.
 *
 * Implements the strict validation rules of the
 * [W3C Trace Context Recommendation §3.2.2.4](https://www.w3.org/TR/trace-context/#versioning-of-traceparent) :
 *
 * - Exactly 55 characters in the canonical version 00 shape :
 *   `00-{32 hex traceId}-{16 hex spanId}-{2 hex flags}`.
 * - All non-dash characters must be lowercase hexadecimal.
 * - The traceId MUST NOT be all zeros (`00…0`) — that is the sentinel
 *   for "invalid trace id".
 * - The spanId MUST NOT be all zeros (`00…0`) — same sentinel.
 * - Only version `00` is recognised. Future versions are treated as
 *   unparseable (return `null`) so the caller can fall back to a
 *   freshly generated context, per the spec's "treat as if no
 *   traceparent received" guidance for malformed input.
 *
 * Returns the parsed components on success, `null` on any failure —
 * never throws. Callers (typically
 * {@see \oihana\middleware\helpers\tracing\traceContextFromRequest()})
 * are expected to silently regenerate on `null`.
 *
 * Why an array instead of a value object : this function extracts the RAW header components only.
 * The current span id is freshly generated by the caller (it is NOT in the incoming header).
 * Putting both into a `TraceContext::fromTraceparent()` static method would conflate parsing (no side effects)
 * with span creation (random bytes call), making testing harder. The intermediate array shape is documented
 * via the strict `return array{...}` annotation.
 *
 * @param string $value The raw `traceparent` header value.
 *
 * @return array{traceId: string, parentSpanId: string, sampled: bool}|null
 *         The parsed components, or `null` when the value is malformed.
 *         Keys exposed as typed constants in {@see ParsedTraceparentField}.
 *
 * @see https://www.w3.org/TR/trace-context/#traceparent-header
 *
 * @author  Marc Alcaraz
 * @package oihana\middleware\tracing
 */
function parseTraceparent( string $value ) : ?array
{
    // Version 00 is the only canonical shape : 2 + 1 + 32 + 1 + 16 + 1 + 2 = 55.
    if ( strlen( $value ) !== 55 )
    {
        return null ;
    }

    if
    (
        preg_match
        (
            '/^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/' ,
            $value ,
            $matches ,
        ) !== 1
    )
    {
        return null ;
    }

    [ , $version , $traceId , $parentSpanId , $flags ] = $matches ;

    // Future versions are intentionally treated as unparseable so the
    // caller falls back to a fresh context — safer than guessing how a
    // version we don't know about lays out its fields.
    if ( $version !== '00' )
    {
        return null ;
    }

    // Sentinel "invalid" values explicitly forbidden by the spec.
    if ( $traceId === '00000000000000000000000000000000' )
    {
        return null ;
    }

    if ( $parentSpanId === '0000000000000000' )
    {
        return null ;
    }

    return
    [
        ParsedTraceparentField::TRACE_ID       => $traceId ,
        ParsedTraceparentField::PARENT_SPAN_ID => $parentSpanId ,
        ParsedTraceparentField::SAMPLED        => ( hexdec( $flags ) & 0x01 ) === 1 ,
        // Only bit 0 of the flags byte is meaningful today (the "sampled" flag).
        // Other bits are reserved — we mask them off to stay forward-compatible.
    ] ;
}
