<?php

declare( strict_types = 1 );

namespace oihana\middleware\tracing ;

/**
 * Resolved W3C Trace Context for the current request.
 *
 * Immutable value object produced by
 * {@see \oihana\middleware\helpers\tracing\traceContextFromRequest()}
 * and consumed by
 * {@see \oihana\middleware\helpers\tracing\withTracingAttribute()} and
 * {@see \oihana\middleware\helpers\tracing\withTraceparentResponseHeader()}.
 *
 * Semantics — see the [W3C Trace Context](https://www.w3.org/TR/trace-context/)
 * recommendation for the canonical reference :
 *
 * - `$traceId` — 32 lowercase hex characters (16 raw bytes) identifying
 *   the end-to-end distributed trace. Inherited from the incoming
 *   `traceparent` when valid, freshly generated otherwise.
 * - `$spanId` — 16 lowercase hex characters (8 raw bytes) identifying
 *   the current span (i.e. this hop). ALWAYS freshly generated by
 *   `traceContextFromRequest()` ; never inherited.
 * - `$parentSpanId` — 16 lowercase hex characters identifying the span
 *   that called this one (extracted from the incoming `traceparent`).
 *   `null` when no valid incoming `traceparent` was received — this
 *   request is then the root of its trace.
 * - `$sampled` — `true` when the trace is recorded for export to the
 *   observability backend. Inherited from the incoming `traceparent`
 *   flags ; defaults to `true` (sampled) when freshly generated, so
 *   first-touch traces are never silently dropped.
 * - `$tracestate` — raw value of the incoming `tracestate` header (or
 *   `null` when absent). Propagated verbatim to downstream calls — the
 *   helper does NOT parse or alter vendor-specific entries.
 *
 * @author  Marc Alcaraz
 * @package oihana\middleware\tracing
 */
final readonly class TraceContext
{
    public function __construct
    (
        public string  $traceId      ,
        public string  $spanId       ,
        public ?string $parentSpanId ,
        public bool    $sampled      ,
        public ?string $tracestate   = null ,
    ) {}

    /**
     * Builds the `traceparent` header value to forward to downstream
     * services or DB drivers that speak W3C Trace Context.
     *
     * Format (W3C Recommendation §3.2) :
     *
     * ```
     * 00-{traceId}-{spanId}-{flags}
     * ```
     *
     * `flags` is `01` when {@see self::$sampled} is `true`, `00`
     * otherwise. The version is always `00` (the only version
     * defined as of the 2021 recommendation).
     *
     * Stamp this on every outgoing HTTP/DB request so the downstream
     * service can continue the trace under the same `$traceId`,
     * recording its own work as a span whose parent is this hop's
     * {@see self::$spanId}.
     *
     * @return string The 55-character `traceparent` header value.
     */
    public function toTraceparent() : string
    {
        $flags = $this->sampled ? '01' : '00' ;

        return '00-' . $this->traceId . '-' . $this->spanId . '-' . $flags ;
    }
}
